name: mongo-sharding

services:
  # Config Server для хранения метаданных шардирования
  config1:
    container_name: config1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27017 --dbpath /data/db
    volumes:
      - config1_data:/data/db
    networks:
      - mongo-network

  # Первый шард (Shard 1)
  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018 --dbpath /data/db
    volumes:
      - shard1_data:/data/db
    networks:
      - mongo-network

  # Второй шард (Shard 2)
  shard2:
    container_name: shard2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27019 --dbpath /data/db
    volumes:
      - shard2_data:/data/db
    networks:
      - mongo-network

  # Mongos Router для маршрутизации запросов
  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/config1:27017 --port 27017
    depends_on:
      - config1
      - shard1
      - shard2
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  # API приложение
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos:27017"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - mongo-network

volumes:
  config1_data:
  shard1_data:
  shard2_data:

networks:
  mongo-network:
    driver: bridge
