services:
  # Config Server для шардирования
  config1:
    container_name: config1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019
    ports:
      - "27019:27019"
    volumes:
      - config1_data:/data/db

  config2:
    container_name: config2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019
    volumes:
      - config2_data:/data/db

  config3:
    container_name: config3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --configsvr --replSet configReplSet --port 27019
    volumes:
      - config3_data:/data/db

  # Mongos Router
  mongos:
    container_name: mongos
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongos --configdb configReplSet/config1:27019,config2:27019,config3:27019 --port 27017 --bind_ip_all
    ports:
      - "27017:27017"
    depends_on:
      - config1
      - config2
      - config3

  # Шард 1 - Реплика 1 (Primary)
  shard1_replica1:
    container_name: shard1_replica1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - "27018:27018"
    volumes:
      - shard1_replica1_data:/data/db

  # Шард 1 - Реплика 2 (Secondary)
  shard1_replica2:
    container_name: shard1_replica2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    volumes:
      - shard1_replica2_data:/data/db

  # Шард 1 - Реплика 3 (Secondary)
  shard1_replica3:
    container_name: shard1_replica3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard1ReplSet --port 27018
    volumes:
      - shard1_replica3_data:/data/db

  # Шард 2 - Реплика 1 (Primary)
  shard2_replica1:
    container_name: shard2_replica1
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020
    ports:
      - "27020:27020"
    volumes:
      - shard2_replica1_data:/data/db

  # Шард 2 - Реплика 2 (Secondary)
  shard2_replica2:
    container_name: shard2_replica2
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020
    volumes:
      - shard2_replica2_data:/data/db

  # Шард 2 - Реплика 3 (Secondary)
  shard2_replica3:
    container_name: shard2_replica3
    image: dh-mirror.gitverse.ru/mongo:latest
    command: mongod --shardsvr --replSet shard2ReplSet --port 27020
    volumes:
      - shard2_replica3_data:/data/db

  # Redis для кеширования
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  # API приложение
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos
      - redis
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos:27017/somedb?retryWrites=true&w=majority&directConnection=false"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

volumes:
  config1_data:
  config2_data:
  config3_data:
  shard1_replica1_data:
  shard1_replica2_data:
  shard1_replica3_data:
  shard2_replica1_data:
  shard2_replica2_data:
  shard2_replica3_data:
  redis_data:
